/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedScriptsIndexRouteImport } from './routes/_authenticated.scripts.index'
import { Route as AuthenticatedScriptsSlugRouteImport } from './routes/_authenticated.scripts.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptsIndexRoute =
  AuthenticatedScriptsIndexRouteImport.update({
    id: '/scripts/',
    path: '/scripts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScriptsSlugRoute =
  AuthenticatedScriptsSlugRouteImport.update({
    id: '/scripts/$slug',
    path: '/scripts/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/scripts/$slug': typeof AuthenticatedScriptsSlugRoute
  '/scripts/': typeof AuthenticatedScriptsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/scripts/$slug': typeof AuthenticatedScriptsSlugRoute
  '/scripts': typeof AuthenticatedScriptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/scripts/$slug': typeof AuthenticatedScriptsSlugRoute
  '/_authenticated/scripts/': typeof AuthenticatedScriptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/scripts/$slug' | '/scripts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/' | '/scripts/$slug' | '/scripts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/'
    | '/_authenticated/scripts/$slug'
    | '/_authenticated/scripts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts/': {
      id: '/_authenticated/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AuthenticatedScriptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts/$slug': {
      id: '/_authenticated/scripts/$slug'
      path: '/scripts/$slug'
      fullPath: '/scripts/$slug'
      preLoaderRoute: typeof AuthenticatedScriptsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedScriptsSlugRoute: typeof AuthenticatedScriptsSlugRoute
  AuthenticatedScriptsIndexRoute: typeof AuthenticatedScriptsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedScriptsSlugRoute: AuthenticatedScriptsSlugRoute,
  AuthenticatedScriptsIndexRoute: AuthenticatedScriptsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
