/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWorkersRouteImport } from './routes/_authenticated.workers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReplRouteImport } from './routes/_authenticated.repl'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated.categories'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedScriptsIndexRouteImport } from './routes/_authenticated.scripts.index'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated.runs.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedScriptsNewRouteImport } from './routes/_authenticated.scripts.new'
import { Route as AuthenticatedScriptsSlugRouteImport } from './routes/_authenticated.scripts.$slug'
import { Route as AuthenticatedRunsIdRouteImport } from './routes/_authenticated.runs.$id'
import { Route as AuthenticatedAdminWorkersRouteImport } from './routes/_authenticated.admin.workers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminStorageRouteImport } from './routes/_authenticated.admin.storage'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated.admin.invites'
import { Route as AuthenticatedAdminWorkersIndexRouteImport } from './routes/_authenticated.admin.workers.index'
import { Route as AuthenticatedScriptsSlugEditRouteImport } from './routes/_authenticated.scripts.$slug.edit'
import { Route as AuthenticatedAdminWorkersIdRouteImport } from './routes/_authenticated.admin.workers.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkersRoute = AuthenticatedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReplRoute = AuthenticatedReplRouteImport.update({
  id: '/repl',
  path: '/repl',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptsIndexRoute =
  AuthenticatedScriptsIndexRouteImport.update({
    id: '/scripts/',
    path: '/scripts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedScriptsNewRoute = AuthenticatedScriptsNewRouteImport.update({
  id: '/scripts/new',
  path: '/scripts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptsSlugRoute =
  AuthenticatedScriptsSlugRouteImport.update({
    id: '/scripts/$slug',
    path: '/scripts/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunsIdRoute = AuthenticatedRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminWorkersRoute =
  AuthenticatedAdminWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStorageRoute =
  AuthenticatedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWorkersIndexRoute =
  AuthenticatedAdminWorkersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminWorkersRoute,
  } as any)
const AuthenticatedScriptsSlugEditRoute =
  AuthenticatedScriptsSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedScriptsSlugRoute,
  } as any)
const AuthenticatedAdminWorkersIdRoute =
  AuthenticatedAdminWorkersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminWorkersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categories': typeof AuthenticatedCategoriesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/repl': typeof AuthenticatedReplRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRouteWithChildren
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/scripts/$slug': typeof AuthenticatedScriptsSlugRouteWithChildren
  '/scripts/new': typeof AuthenticatedScriptsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
  '/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/admin/workers/$id': typeof AuthenticatedAdminWorkersIdRoute
  '/scripts/$slug/edit': typeof AuthenticatedScriptsSlugEditRoute
  '/admin/workers/': typeof AuthenticatedAdminWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/repl': typeof AuthenticatedReplRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/scripts/$slug': typeof AuthenticatedScriptsSlugRouteWithChildren
  '/scripts/new': typeof AuthenticatedScriptsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
  '/scripts': typeof AuthenticatedScriptsIndexRoute
  '/admin/workers/$id': typeof AuthenticatedAdminWorkersIdRoute
  '/scripts/$slug/edit': typeof AuthenticatedScriptsSlugEditRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/repl': typeof AuthenticatedReplRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workers': typeof AuthenticatedWorkersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workers': typeof AuthenticatedAdminWorkersRouteWithChildren
  '/_authenticated/runs/$id': typeof AuthenticatedRunsIdRoute
  '/_authenticated/scripts/$slug': typeof AuthenticatedScriptsSlugRouteWithChildren
  '/_authenticated/scripts/new': typeof AuthenticatedScriptsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
  '/_authenticated/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/_authenticated/admin/workers/$id': typeof AuthenticatedAdminWorkersIdRoute
  '/_authenticated/scripts/$slug/edit': typeof AuthenticatedScriptsSlugEditRoute
  '/_authenticated/admin/workers/': typeof AuthenticatedAdminWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/categories'
    | '/profile'
    | '/repl'
    | '/settings'
    | '/workers'
    | '/admin/invites'
    | '/admin/storage'
    | '/admin/users'
    | '/admin/workers'
    | '/runs/$id'
    | '/scripts/$slug'
    | '/scripts/new'
    | '/admin/'
    | '/runs/'
    | '/scripts/'
    | '/admin/workers/$id'
    | '/scripts/$slug/edit'
    | '/admin/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/categories'
    | '/profile'
    | '/repl'
    | '/settings'
    | '/workers'
    | '/'
    | '/admin/invites'
    | '/admin/storage'
    | '/admin/users'
    | '/runs/$id'
    | '/scripts/$slug'
    | '/scripts/new'
    | '/admin'
    | '/runs'
    | '/scripts'
    | '/admin/workers/$id'
    | '/scripts/$slug/edit'
    | '/admin/workers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/categories'
    | '/_authenticated/profile'
    | '/_authenticated/repl'
    | '/_authenticated/settings'
    | '/_authenticated/workers'
    | '/_authenticated/'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/storage'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workers'
    | '/_authenticated/runs/$id'
    | '/_authenticated/scripts/$slug'
    | '/_authenticated/scripts/new'
    | '/_authenticated/admin/'
    | '/_authenticated/runs/'
    | '/_authenticated/scripts/'
    | '/_authenticated/admin/workers/$id'
    | '/_authenticated/scripts/$slug/edit'
    | '/_authenticated/admin/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workers': {
      id: '/_authenticated/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthenticatedWorkersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repl': {
      id: '/_authenticated/repl'
      path: '/repl'
      fullPath: '/repl'
      preLoaderRoute: typeof AuthenticatedReplRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts/': {
      id: '/_authenticated/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AuthenticatedScriptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/scripts/new': {
      id: '/_authenticated/scripts/new'
      path: '/scripts/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof AuthenticatedScriptsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts/$slug': {
      id: '/_authenticated/scripts/$slug'
      path: '/scripts/$slug'
      fullPath: '/scripts/$slug'
      preLoaderRoute: typeof AuthenticatedScriptsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/$id': {
      id: '/_authenticated/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AuthenticatedRunsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workers': {
      id: '/_authenticated/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AuthenticatedAdminWorkersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/storage': {
      id: '/_authenticated/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AuthenticatedAdminStorageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/workers/': {
      id: '/_authenticated/admin/workers/'
      path: '/'
      fullPath: '/admin/workers/'
      preLoaderRoute: typeof AuthenticatedAdminWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminWorkersRoute
    }
    '/_authenticated/scripts/$slug/edit': {
      id: '/_authenticated/scripts/$slug/edit'
      path: '/edit'
      fullPath: '/scripts/$slug/edit'
      preLoaderRoute: typeof AuthenticatedScriptsSlugEditRouteImport
      parentRoute: typeof AuthenticatedScriptsSlugRoute
    }
    '/_authenticated/admin/workers/$id': {
      id: '/_authenticated/admin/workers/$id'
      path: '/$id'
      fullPath: '/admin/workers/$id'
      preLoaderRoute: typeof AuthenticatedAdminWorkersIdRouteImport
      parentRoute: typeof AuthenticatedAdminWorkersRoute
    }
  }
}

interface AuthenticatedAdminWorkersRouteChildren {
  AuthenticatedAdminWorkersIdRoute: typeof AuthenticatedAdminWorkersIdRoute
  AuthenticatedAdminWorkersIndexRoute: typeof AuthenticatedAdminWorkersIndexRoute
}

const AuthenticatedAdminWorkersRouteChildren: AuthenticatedAdminWorkersRouteChildren =
  {
    AuthenticatedAdminWorkersIdRoute: AuthenticatedAdminWorkersIdRoute,
    AuthenticatedAdminWorkersIndexRoute: AuthenticatedAdminWorkersIndexRoute,
  }

const AuthenticatedAdminWorkersRouteWithChildren =
  AuthenticatedAdminWorkersRoute._addFileChildren(
    AuthenticatedAdminWorkersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminStorageRoute: typeof AuthenticatedAdminStorageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkersRoute: typeof AuthenticatedAdminWorkersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminStorageRoute: AuthenticatedAdminStorageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkersRoute: AuthenticatedAdminWorkersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedScriptsSlugRouteChildren {
  AuthenticatedScriptsSlugEditRoute: typeof AuthenticatedScriptsSlugEditRoute
}

const AuthenticatedScriptsSlugRouteChildren: AuthenticatedScriptsSlugRouteChildren =
  {
    AuthenticatedScriptsSlugEditRoute: AuthenticatedScriptsSlugEditRoute,
  }

const AuthenticatedScriptsSlugRouteWithChildren =
  AuthenticatedScriptsSlugRoute._addFileChildren(
    AuthenticatedScriptsSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReplRoute: typeof AuthenticatedReplRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkersRoute: typeof AuthenticatedWorkersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRunsIdRoute: typeof AuthenticatedRunsIdRoute
  AuthenticatedScriptsSlugRoute: typeof AuthenticatedScriptsSlugRouteWithChildren
  AuthenticatedScriptsNewRoute: typeof AuthenticatedScriptsNewRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
  AuthenticatedScriptsIndexRoute: typeof AuthenticatedScriptsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReplRoute: AuthenticatedReplRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkersRoute: AuthenticatedWorkersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRunsIdRoute: AuthenticatedRunsIdRoute,
  AuthenticatedScriptsSlugRoute: AuthenticatedScriptsSlugRouteWithChildren,
  AuthenticatedScriptsNewRoute: AuthenticatedScriptsNewRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
  AuthenticatedScriptsIndexRoute: AuthenticatedScriptsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
